{"record": {"timestamp": 1686270093284, "time": "2023-06-09 08:21:33", "exception": null, "message": "Traceback (most recent call last):\n  File \"/Users/zhouzhiyong/Desktop/EasyAirflow/rest_api/utils/response_safe.py\", line 40, in wraps\n    resp = f(*args, **kwargs)\n  File \"/Users/zhouzhiyong/Desktop/EasyAirflow/rest_api/endpoints/resources/task_instance_list_resource.py\", line 87, in post\n    TaskHandlers.back_fill(dag_id, task_id, start_date, end_date)\n  File \"/Users/zhouzhiyong/Desktop/EasyAirflow/rest_api/endpoints/handlers/airflow_task_handlers.py\", line 202, in back_fill\n    dag.run(\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/models/dag.py\", line 2490, in run\n    run_job(job=job, execute_callable=job_runner._execute)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/utils/session.py\", line 76, in wrapper\n    return func(*args, session=session, **kwargs)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/jobs/job.py\", line 281, in run_job\n    return execute_job(job, execute_callable=execute_callable)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/jobs/job.py\", line 310, in execute_job\n    ret = execute_callable()\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/utils/session.py\", line 76, in wrapper\n    return func(*args, session=session, **kwargs)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/jobs/backfill_job_runner.py\", line 919, in _execute\n    self._execute_dagruns(\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/utils/session.py\", line 73, in wrapper\n    return func(*args, **kwargs)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/jobs/backfill_job_runner.py\", line 806, in _execute_dagruns\n    processed_dag_run_dates = self._process_backfill_task_instances(\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/jobs/backfill_job_runner.py\", line 657, in _process_backfill_task_instances\n    executor.heartbeat()\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/executors/base_executor.py\", line 224, in heartbeat\n    self.trigger_tasks(open_slots)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/executors/base_executor.py\", line 282, in trigger_tasks\n    self._process_tasks(task_tuples)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/executors/celery_executor.py\", line 259, in _process_tasks\n    key_and_async_results = self._send_tasks_to_celery(task_tuples_to_send)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/site-packages/airflow/executors/celery_executor.py\", line 306, in _send_tasks_to_celery\n    key_and_async_results = list(\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/concurrent/futures/process.py\", line 575, in _chain_from_iterable_of_lists\n    for element in iterable:\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/concurrent/futures/_base.py\", line 621, in result_iterator\n    yield _result_or_cancel(fs.pop())\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/concurrent/futures/_base.py\", line 319, in _result_or_cancel\n    return fut.result(timeout)\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/concurrent/futures/_base.py\", line 458, in result\n    return self.__get_result()\n  File \"/Users/zhouzhiyong/opt/anaconda3/envs/EasyAirflow/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\nconcurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.\n", "file": "response_safe.py", "line": 45, "function": "wraps", "level": "ERROR", "name": "utils.response_safe", "process": 33581, "thread": 13220290560, "extra": {}}, "trace": {"service": "airflow-plus", "hostname": "zhouzhiyongdeMac-mini.local", "span_name": null, "span_id": "0000000000000000", "trace_id": "57ee04b29fa540951e024b1496b33f9c", "parent_span_id": null}}
